### ISSUE TITLE
Push your changes to dev branch after initial commit

### ISSUE THREAD

**Issue by firatagdas** [scerenavci/Block-Breaker#6]
There is a logic behind branches. 

**master** branch should always the stable version.
**develop** (or dev) branch is your development branch that you can push every changes in it. Once you sure develop reached stable state, you can merge with **master** branch.

You can read the really nice blog about git flow. So you 'll get organised git repo: http://nvie.com/posts/a-successful-git-branching-model/

**Comment by scerenavci** [comment]
Roger that :dancer:
